{% set name = "lame" %}
{% set version = "3.100" %}
{% set sha256 = "ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/sourceforge/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }} 
  patches:
    - libmp3lame.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # seems to be minor version compatibility
    # https://abi-laboratory.pro/tracker/timeline/lame/
    - {{ pin_subpackage('lame', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - lame --genre-list testcase.mp3

about:
  home: https://lame.sourceforge.io/
  license: LGPL
  license_file: LICENSE
  summary: 'High quality MPEG Audio Layer III (MP3) encoder'
  description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder licensed under the LGPL.
    Today, LAME is considered the best MP3 encoder at mid-high bitrates and at VBR, mostly
    thanks to the dedicated work of its developers and the open source licensing model
    that allowed the project to tap into engineering resources from all around the world.
  doc_url: http://lame.sourceforge.net/using.php
  dev_url: https://svn.code.sf.net/p/lame/svn/trunk/lame/
